# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic
    - gosec
  disable:
    - unparam  # Produces false positives for interface method implementations
    - prealloc  # Premature optimization, not critical for correctness

linters-settings:
  errcheck:
    check-blank: false  # Too noisy for existing code
  govet:
    enable:
      - printf
      - shift
      - structtag
      - nilness
    disable:
      - shadow  # Variable shadowing is acceptable in many cases
      - fieldalignment  # Micro-optimization, not critical
  gofmt:
    simplify: true
  misspell:
    locale: US
  gosec:
    excludes:
      - G104  # Audit errors not checked (too noisy)
      - G114  # HTTP server timeouts (will be addressed separately)
      - G301  # Directory permissions (0755 is standard for log directories)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    # Exclude fieldalignment errors (micro-optimization, not critical)
    - "fieldalignment:"
    # Exclude specific unchecked errors that are intentional
    - "Error return value of `.*Body.Close` is not checked"
    - "Error return value of `.*AnswerCallbackQuery` is not checked"
    - "Error return value of `.*SendMessage` is not checked"
    - "Error return value of `.*Encode` is not checked"
    # Exclude HTTP timeout warnings (will be addressed separately)
    - "G114:"
    # Exclude directory permissions (0755 is standard)
    - "G301:"
    # Exclude exitAfterDefer in main.go (acceptable for fatal errors)
    - "exitAfterDefer:"
    # Exclude nil check before len (defensive programming)
    - "S1009:"
    # Exclude empty branch warnings (intentional error handling)
    - "SA9003:"
    # Allow British spelling "cancelled"
    - "cancelled.*misspelling.*canceled"
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    # Exclude duplicate code check for test files
    - path: _test\.go
      linters:
        - dupl
