# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
    - gosec
    - prealloc

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable-all: true
  gofmt:
    simplify: true
  misspell:
    locale: US
  gosec:
    excludes:
      - G104  # Audit errors not checked (too noisy)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - unparam
        - errcheck
    # Exclude duplicate code check for test files
    - path: _test\.go
      linters:
        - dupl
